shortener/urls.py
from django.urls import path
from .views import home, go

app_name = 'shortener'
urlpatterns = [
    path('', home, name='home'),
    path('go/', go, name='go'),
]

urlshortener/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shortener.urls'))
]

shortener/models.py
from django.db import models

from .utils import create_shortcode


class ShortURL(models.Model):
    url = models.URLField(max_length=220)
    shortcode = models.CharField(max_length=15, unique=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.url

    def save(self, *args, **kwargs):
        if self.shortcode == "":
            self.shortcode = create_shortcode(self)
        super(ShortURL, self).save(*args, **kwargs)

shortener/forms.py
from django import forms

from .models import ShortURL


class URLForm(forms.ModelForm):
    class Meta:
        model = ShortURL
        fields = '__all__'

shortener/views.py
from django.shortcuts import render, redirect

from .forms import URLForm
from .models import ShortURL


def home(request):
    form = URLForm()
    if request.method == 'POST':
        form = URLForm(request.POST)
        if form.is_valid():
            url = form.cleaned_data['url']
            short_url = ShortURL.objects.create(url=url)
            form = URLForm(
                initial={'url': url, 'shortcode': short_url.shortcode})
    return render(request, 'shortener/home.html', {'form': form})


def go(request):
    shortcode = request.GET.get('code', None)
    if shortcode:
        url = ShortURL.objects.get(shortcode=shortcode).url
        return redirect(url)
    return render(request, 'shortener/go.html')

shortener/templates/shortener/go.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Go</title>
</head>
<body>
    <h1>Enter a code to go to its url</h1>
    <form method="GET">
        <input type="text" name="code" id="">
        <input type="submit">
    </form>

</body>
</html>

shortener/templates/shortener/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>
    <h1>Enter a url to get a code</h1>
    <form method="POST">
        {% csrf_token %}
        {{form}}
        <br>
        <input type="submit" value="Generate ShortURL">
    </form>

    <a href="{% url 'shortener:go' %}">Have a shortcode? Access its URL here</a>

</body>
</html>